<a href="https://colab.research.google.com/github/DanielRaiicHu/numPy/blob/main/numPy.ipynb?forceRefresh=true">
  <img src="https://drive.google.com/uc?id=191Woxwut0iaIL2hCcCIeXRSB6oba_88H" alt="Abrir en Colab" width="120"/>
</a>


Numpy: Análisis numérico eficiente con Python
NumPy es una biblioteca de Python que ofrece diversas herramientas y funcionalidades esenciales para la computación científica, incluyendo objetos de matriz multidimensional conocidos como arrays, rutinas para operaciones rápidas en matrizes, además de operaciones matemáticas, manipulación de formas, estadística entre otros. Es ampliamente utilizada en áreas como análisis de datos, procesamiento de señales y aprendizaje de máquina.

Para acceder a la documentación de esta biblioteca, puedes hacer clic en el siguiente enlace: https://numpy.org/devdocs/index.html





In [4]:
import numpy as np

ano_inicial = 2002
ano_final = 2102

#arange(inicio, fin, paso) se utiliza para crear un array de valores en un rango específico
np.arange(ano_inicial, ano_final + 1, 4)

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [21]:
import numpy as np

In [22]:
#no funciona porque el primer dato es nulo, por eso mas abajo ocuparemos arange() para que comience en 1 hacia adelante
url = "https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv"

np.loadtxt(url, delimiter=",")

ValueError: could not convert string '' to float64 at row 0, column 1.

In [13]:
# 7 * 12 + 3 cantidad de meses -> 7 años x 12 meses, + 3 meses = 87
np.arange(1,88,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87])

1) Cargar desde un Gist de GitHub: En la primera forma, utilizamos un enlace "raw" de un Gist de GitHub que contenía el archivo CSV. Copiamos la URL y la almacenamos en una variable. Luego, utilizamos la función np.loadtxt() de NumPy, especificando la URL como el nombre del archivo y el delimitador (coma) para cargar los datos directamente desde el Gist.

In [31]:
url ="https://gist.githubusercontent.com/ahcamachod/41b8a65c5e5b58125401deafb68af460/raw/f84320f69efa1cc3e86e1db054422cfa4869c63e/manzanas.csv"
np.loadtxt(url, delimiter=",", usecols = np.arange(1,88,1)) #carga dataset con delimitador "," y mostrando las columnas del array del rango (precios de manzanas)

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.2020,   2.2020,   3.2020],
       [ 

2) Cargar desde Google Drive: En la segunda forma, montamos Google Drive en nuestro notebook de Google Colab. Luego, especificamos la ruta del archivo manzanas.csv almacenado en Google Drive y utilizamos nuevamente np.loadtxt() para cargar los datos, asegurándonos de que la ruta sea correcta y que el delimitador esté configurado adecuadamente.

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [36]:
import numpy as np
ruta = "/content/drive/MyDrive/manzanas.csv"
np.loadtxt(ruta, delimiter=",", usecols = np.arange(1,88,1))


array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.2020,   2.2020,   3.2020],
       [ 

In [38]:
datos = np.loadtxt(ruta, delimiter=",", usecols = np.arange(1,88,1)) #almacenamos los datos

______

# **Para saber más: ventajas de los arrays**

Aquí tienes un ejemplo de cómo convertir una lista en un array Numpy:

In [39]:
import numpy as np

# crea una lista
lista = [1, 2, 3, 4, 5]

# convierte la lista en un array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)

Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


Existen varias ventajas en el uso de arrays Numpy en lugar de listas regulares de Python y aquí tienes algunas de ellas:

**1.** Eficiencia de procesamiento: Las operaciones matemáticas en los arrays Numpy son mucho más rápidas que en las listas regulares, ya que Numpy está optimizado para trabajar con conjuntos de datos homogéneos y libera memoria de la computadora de manera rápida.

**2.** Facilidad de uso: Las operaciones matemáticas en los arrays Numpy se expresan de manera mucho más clara y concisa que en las listas regulares, lo que hace que el código sea más fácil de leer y mantener.

**3.** Integración con otras bibliotecas: Numpy es una de las bibliotecas más utilizadas en ciencia de datos y aprendizaje automático. Muchas otras bibliotecas, como Pandas y Matplotlib, están diseñadas para trabajar directamente con arrays Numpy.

**Comparación de rendimiento: listas vs arrays**

Centrándonos en la eficiencia, podemos comparar el tiempo necesario para realizar un cálculo utilizando listas y arrays.

In [45]:
import numpy as np
import time

# crea una lista con 1000000 elementos
lista = list(range(1000000))

# convierte la lista en un array Numpy
array = np.array(lista)

# comienza a medir el tiempo para la operación con la lista
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento de la lista
lista_cuadrado = [i**2 for i in lista]

# detiene el cronómetro
tiempo_lista = time.time() - start_time

# comienza a medir el tiempo para la operación con el array
start_time = time.time()

# realiza la operación de elevar al cuadrado cada elemento del array
array_cuadrado = array**2

# detiene el cronómetro
tiempo_array = time.time() - start_time

print("Tiempo de la operación con la lista: ", tiempo_lista)
print("Tiempo de la operación con el array: ", tiempo_array)

#El tiempo de operación con array es mucho más rápida.

Tiempo de la operación con la lista:  0.09795832633972168
Tiempo de la operación con el array:  0.0036344528198242188


______

In [47]:
datos.ndim

2

In [48]:
datos.shape

(6, 87)

In [49]:
datos

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.2020,   2.2020,   3.2020],
       [ 

In [50]:
datos.T

array([[  1.2013,  79.7200,  42.6700,  62.5500,  48.2600,  71.2500],
       [  2.2013,  81.0800,  44.3700,  62.7300,  51.0100,  71.3500],
       [  3.2013,  79.6800,  44.7300,  63.4300,  50.9100,  70.9000],
       [  4.2013,  79.8000,  46.7500,  63.8300,  53.9400,  71.9200],
       [  5.2013,  80.6300,      nan,  66.0600,  61.2700,  72.9100],
       [  6.2013,  80.8000,  51.5900,  69.2200,  65.4400,  74.3900],
       [  7.2013,  80.2800,  57.8000,  72.0700,  56.5100,  73.1000],
       [  8.2013,  78.9900,  62.1400,  69.3100,  53.0000,  70.2400],
       [  9.2013,  76.7700,  56.7600,  65.1800,  43.8700,  69.1200],
       [ 10.2013,  76.0900,  50.8500,  62.1300,  42.1200,  68.9800],
       [ 11.2013,  76.3600,  46.4300,  64.1700,  43.9800,  68.5800],
       [ 12.2013,  77.1600,  46.7300,  65.5000,  44.6600,  69.5000],
       [  1.2014,  77.5000,  45.8500,  66.8500,  47.7300,  70.1400],
       [  2.2014,  79.0300,  49.2500,  68.3800,  52.3100,  70.5800],
       [  3.2014,  80.2800,  48.14

In [53]:
datos_transpuestos = datos.T

In [54]:
datos_transpuestos

array([[  1.2013,  79.7200,  42.6700,  62.5500,  48.2600,  71.2500],
       [  2.2013,  81.0800,  44.3700,  62.7300,  51.0100,  71.3500],
       [  3.2013,  79.6800,  44.7300,  63.4300,  50.9100,  70.9000],
       [  4.2013,  79.8000,  46.7500,  63.8300,  53.9400,  71.9200],
       [  5.2013,  80.6300,      nan,  66.0600,  61.2700,  72.9100],
       [  6.2013,  80.8000,  51.5900,  69.2200,  65.4400,  74.3900],
       [  7.2013,  80.2800,  57.8000,  72.0700,  56.5100,  73.1000],
       [  8.2013,  78.9900,  62.1400,  69.3100,  53.0000,  70.2400],
       [  9.2013,  76.7700,  56.7600,  65.1800,  43.8700,  69.1200],
       [ 10.2013,  76.0900,  50.8500,  62.1300,  42.1200,  68.9800],
       [ 11.2013,  76.3600,  46.4300,  64.1700,  43.9800,  68.5800],
       [ 12.2013,  77.1600,  46.7300,  65.5000,  44.6600,  69.5000],
       [  1.2014,  77.5000,  45.8500,  66.8500,  47.7300,  70.1400],
       [  2.2014,  79.0300,  49.2500,  68.3800,  52.3100,  70.5800],
       [  3.2014,  80.2800,  48.14

_______

Otro Ejemplo de `.shape`:

In [55]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dato = np.loadtxt(url, delimiter=',', skiprows=1, dtype=float) #skiprows=1 omite la primera fila
dato.shape

(12, 2)

_____


# **Haga lo que hicimos**

Ha llegado el momento de poner a prueba los conocimientos adquiridos durante la lección. Para ello, vamos a utilizar otro conjunto de datos en un desafío que se desarrollará a lo largo del curso. Este conjunto de datos es una versión modificada del [archivo](https://www.kaggle.com/datasets/joshmcadams/oranges-vs-grapefruit) disponible en el sitio de Kaggle. Por lo tanto, utilizaremos el [archivo raw](https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv) disponible en Github.

En esta etapa, debes cargar los datos. Para hacerlo, importa NumPy y utiliza la función loadtxt. Utiliza el enlace de la URL y el parámetro usecols para omitir la primera columna. Puedes usar np.arange para crear la secuencia de números que representan las columnas. Por último, también es necesario incluir el parámetro skiprows=1 para que la primera línea de texto se omita al leer el archivo.



In [70]:
import numpy as np
enlace = "https://gist.githubusercontent.com/ahcamachod/9be09de793dc3bf1e6c3d98eb4e5b1ef/raw/21b85572693200040e11284ef6dcfc3457ec8e11/citrus.csv"

carga_datos = np.loadtxt(enlace,delimiter=",",usecols= np.arange(1,6,1),skiprows=1)
carga_datos

array([[  2.9600,  86.7600, 172.0000,  85.0000,   2.0000],
       [  3.9100,  88.0500, 166.0000,  78.0000,   3.0000],
       [  4.4200,  95.1700, 156.0000,  81.0000,   2.0000],
       ...,
       [ 15.5900, 256.5000, 168.0000,  82.0000,  20.0000],
       [ 15.9200, 260.1400, 142.0000,  72.0000,  11.0000],
       [ 16.4500, 261.5100, 152.0000,  74.0000,   2.0000]])

_____